/**
 * ============================================================
 *  XATIRCHI TUMANI - 70 TA MFY VA BAZA STATISTIKASI
 *
 *  Manba: tuman hokimligining 31.08.2026 holatiga svod jadvali
 *  ("Kambag'allikdan farovonlik sari" dasturi).
 *
 *  Bu raqamlar QAMROV FOIZINING MAXRAJI. Ularsiz platforma faqat
 *  o'zi yig'ganini sanay oladi; ular bilan esa "51 ta ishsizdan
 *  38 tasi xatlovdan o'tdi = 75%" deb ayta oladi. Aynan shu
 *  ko'rsatkich hokimga qaysi mahalla orqada qolayotganini
 *  ko'rsatadi.
 *
 *  Nomlar ikki alifboda saqlanadi: anketa kirillda to'ldiriladi
 *  (xodim qo'lidagi qog'oz kirill), panel esa lotinda ko'rsatadi.
 * ============================================================
 */

export interface MahallaBazasi {
  /** Svod jadvalidagi tartib raqami */
  tartib: number;
  nomi: string;
  nomiKirill: string;
  aholi: number;
  xonadon: number;
  oila: number;
  /** 01.01.2026 holatiga kambag'al oilalar */
  kambagalYanvar: number;
  /** 01.08.2026 holatiga umumiy kambag'al oilalar */
  kambagalJami: number;
  davlatTaminotida: number;
  kambagalOilalar: number;
  kambagallikChegarasida: number;
  mehnatgaLayoqatli: number;
  band: number;
  /** Ishsizlar soni - platformaning asosiy maxraji */
  ishsiz: number;
  ayollarDaftari: number;
  ijtimoiyReestr: number;
  migratsiyadanQaytgan: number;
  oliyBitiruvchi: number;
  ortaMaxsusBitiruvchi: number;
  maktabBitiruvchi: number;
}

export const MAHALLALAR_BAZASI: MahallaBazasi[] = [
  {
    tartib: 1,
    nomi: "Uyshun",
    nomiKirill: "Уйшун",
    aholi: 2582,
    xonadon: 506,
    oila: 659,
    kambagalYanvar: 59,
    kambagalJami: 128,
    davlatTaminotida: 34,
    kambagalOilalar: 88,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 972,
    band: 925,
    ishsiz: 51,
    ayollarDaftari: 20,
    ijtimoiyReestr: 22,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 2,
    nomi: "Alisher Navoiy",
    nomiKirill: "Алишер Навоий",
    aholi: 3512,
    xonadon: 635,
    oila: 805,
    kambagalYanvar: 99,
    kambagalJami: 145,
    davlatTaminotida: 49,
    kambagalOilalar: 93,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1322,
    band: 1146,
    ishsiz: 66,
    ayollarDaftari: 35,
    ijtimoiyReestr: 18,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 3,
    nomi: "Xo'jaqulobod",
    nomiKirill: "Хўжақулобод",
    aholi: 3489,
    xonadon: 610,
    oila: 751,
    kambagalYanvar: 94,
    kambagalJami: 153,
    davlatTaminotida: 57,
    kambagalOilalar: 88,
    kambagallikChegarasida: 18,
    mehnatgaLayoqatli: 1313,
    band: 1241,
    ishsiz: 64,
    ayollarDaftari: 25,
    ijtimoiyReestr: 27,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 4,
    nomi: "Amir Temur",
    nomiKirill: "Амир Темур",
    aholi: 3482,
    xonadon: 628,
    oila: 739,
    kambagalYanvar: 78,
    kambagalJami: 115,
    davlatTaminotida: 25,
    kambagalOilalar: 74,
    kambagallikChegarasida: 17,
    mehnatgaLayoqatli: 1310,
    band: 1272,
    ishsiz: 43,
    ayollarDaftari: 18,
    ijtimoiyReestr: 14,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 5,
    nomi: "Bo'g'irdoq",
    nomiKirill: "Буғирдоқ",
    aholi: 3115,
    xonadon: 649,
    oila: 859,
    kambagalYanvar: 70,
    kambagalJami: 118,
    davlatTaminotida: 25,
    kambagalOilalar: 78,
    kambagallikChegarasida: 18,
    mehnatgaLayoqatli: 1172,
    band: 1060,
    ishsiz: 40,
    ayollarDaftari: 25,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 6,
    nomi: "Oltinobod",
    nomiKirill: "Олтинобод",
    aholi: 3210,
    xonadon: 661,
    oila: 884,
    kambagalYanvar: 73,
    kambagalJami: 106,
    davlatTaminotida: 30,
    kambagalOilalar: 77,
    kambagallikChegarasida: 15,
    mehnatgaLayoqatli: 1208,
    band: 1098,
    ishsiz: 41,
    ayollarDaftari: 28,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 7,
    nomi: "Koriz Arab",
    nomiKirill: "Кориз Араб",
    aholi: 2820,
    xonadon: 506,
    oila: 708,
    kambagalYanvar: 62,
    kambagalJami: 93,
    davlatTaminotida: 30,
    kambagalOilalar: 59,
    kambagallikChegarasida: 16,
    mehnatgaLayoqatli: 1061,
    band: 1007,
    ishsiz: 44,
    ayollarDaftari: 20,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 8,
    nomi: "Damariq",
    nomiKirill: "Дамариқ",
    aholi: 3072,
    xonadon: 601,
    oila: 682,
    kambagalYanvar: 84,
    kambagalJami: 112,
    davlatTaminotida: 49,
    kambagalOilalar: 55,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1156,
    band: 1086,
    ishsiz: 62,
    ayollarDaftari: 30,
    ijtimoiyReestr: 21,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 9,
    nomi: "Quchchi",
    nomiKirill: "Қуччи",
    aholi: 2080,
    xonadon: 438,
    oila: 648,
    kambagalYanvar: 61,
    kambagalJami: 87,
    davlatTaminotida: 28,
    kambagalOilalar: 52,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 783,
    band: 731,
    ishsiz: 44,
    ayollarDaftari: 27,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 1,
    oliyBitiruvchi: 2,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 10,
    nomi: "Mustaqillik",
    nomiKirill: "Мустақиллик",
    aholi: 4503,
    xonadon: 748,
    oila: 942,
    kambagalYanvar: 77,
    kambagalJami: 97,
    davlatTaminotida: 29,
    kambagalOilalar: 76,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 1695,
    band: 1645,
    ishsiz: 62,
    ayollarDaftari: 15,
    ijtimoiyReestr: 36,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 11,
    nomi: "Galabek",
    nomiKirill: "Галабек",
    aholi: 3428,
    xonadon: 562,
    oila: 839,
    kambagalYanvar: 61,
    kambagalJami: 98,
    davlatTaminotida: 29,
    kambagalOilalar: 64,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1290,
    band: 1310,
    ishsiz: 87,
    ayollarDaftari: 36,
    ijtimoiyReestr: 33,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 9,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 12,
    nomi: "Chag'atoy",
    nomiKirill: "Чағатой",
    aholi: 3112,
    xonadon: 545,
    oila: 781,
    kambagalYanvar: 51,
    kambagalJami: 95,
    davlatTaminotida: 30,
    kambagalOilalar: 59,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1171,
    band: 1011,
    ishsiz: 54,
    ayollarDaftari: 25,
    ijtimoiyReestr: 19,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 13,
    nomi: "Xo'jaqo'rg'on",
    nomiKirill: "Хўжақўрғон",
    aholi: 2522,
    xonadon: 578,
    oila: 801,
    kambagalYanvar: 44,
    kambagalJami: 93,
    davlatTaminotida: 24,
    kambagalOilalar: 59,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 949,
    band: 822,
    ishsiz: 57,
    ayollarDaftari: 33,
    ijtimoiyReestr: 12,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 14,
    nomi: "Nayman",
    nomiKirill: "Найман",
    aholi: 3080,
    xonadon: 541,
    oila: 726,
    kambagalYanvar: 53,
    kambagalJami: 89,
    davlatTaminotida: 30,
    kambagalOilalar: 50,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 1159,
    band: 1150,
    ishsiz: 49,
    ayollarDaftari: 22,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 8,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 15,
    nomi: "Mirdosh",
    nomiKirill: "Мирдош",
    aholi: 2344,
    xonadon: 469,
    oila: 662,
    kambagalYanvar: 65,
    kambagalJami: 87,
    davlatTaminotida: 28,
    kambagalOilalar: 46,
    kambagallikChegarasida: 18,
    mehnatgaLayoqatli: 1174,
    band: 921,
    ishsiz: 43,
    ayollarDaftari: 20,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 16,
    nomi: "Paxtakor",
    nomiKirill: "Пахтакор",
    aholi: 2533,
    xonadon: 518,
    oila: 678,
    kambagalYanvar: 44,
    kambagalJami: 67,
    davlatTaminotida: 22,
    kambagalOilalar: 46,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 953,
    band: 883,
    ishsiz: 39,
    ayollarDaftari: 28,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 17,
    nomi: "Changir",
    nomiKirill: "Чангир",
    aholi: 2781,
    xonadon: 540,
    oila: 720,
    kambagalYanvar: 67,
    kambagalJami: 95,
    davlatTaminotida: 34,
    kambagalOilalar: 54,
    kambagallikChegarasida: 15,
    mehnatgaLayoqatli: 1047,
    band: 789,
    ishsiz: 47,
    ayollarDaftari: 22,
    ijtimoiyReestr: 14,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 18,
    nomi: "Langar",
    nomiKirill: "Лангар",
    aholi: 2808,
    xonadon: 614,
    oila: 719,
    kambagalYanvar: 75,
    kambagalJami: 90,
    davlatTaminotida: 33,
    kambagalOilalar: 43,
    kambagallikChegarasida: 23,
    mehnatgaLayoqatli: 1057,
    band: 934,
    ishsiz: 44,
    ayollarDaftari: 13,
    ijtimoiyReestr: 18,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 19,
    nomi: "Ko'ksaroy",
    nomiKirill: "Кўксарой",
    aholi: 3179,
    xonadon: 609,
    oila: 832,
    kambagalYanvar: 70,
    kambagalJami: 105,
    davlatTaminotida: 40,
    kambagalOilalar: 56,
    kambagallikChegarasida: 14,
    mehnatgaLayoqatli: 1196,
    band: 1082,
    ishsiz: 68,
    ayollarDaftari: 33,
    ijtimoiyReestr: 22,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 20,
    nomi: "Farovon",
    nomiKirill: "Фаровон",
    aholi: 1764,
    xonadon: 573,
    oila: 689,
    kambagalYanvar: 59,
    kambagalJami: 86,
    davlatTaminotida: 34,
    kambagalOilalar: 48,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 664,
    band: 431,
    ishsiz: 34,
    ayollarDaftari: 10,
    ijtimoiyReestr: 14,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 21,
    nomi: "Zarbdor",
    nomiKirill: "Зарбдор",
    aholi: 2351,
    xonadon: 503,
    oila: 735,
    kambagalYanvar: 38,
    kambagalJami: 72,
    davlatTaminotida: 28,
    kambagalOilalar: 49,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 885,
    band: 745,
    ishsiz: 43,
    ayollarDaftari: 21,
    ijtimoiyReestr: 8,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 22,
    nomi: "Uchtepa",
    nomiKirill: "Учтепа",
    aholi: 3147,
    xonadon: 526,
    oila: 738,
    kambagalYanvar: 62,
    kambagalJami: 81,
    davlatTaminotida: 19,
    kambagalOilalar: 47,
    kambagallikChegarasida: 16,
    mehnatgaLayoqatli: 1184,
    band: 1200,
    ishsiz: 64,
    ayollarDaftari: 30,
    ijtimoiyReestr: 22,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 23,
    nomi: "Oq-oltin",
    nomiKirill: "Оқ Олтин",
    aholi: 3630,
    xonadon: 544,
    oila: 739,
    kambagalYanvar: 52,
    kambagalJami: 80,
    davlatTaminotida: 27,
    kambagalOilalar: 47,
    kambagallikChegarasida: 11,
    mehnatgaLayoqatli: 1366,
    band: 1036,
    ishsiz: 56,
    ayollarDaftari: 30,
    ijtimoiyReestr: 8,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 24,
    nomi: "Sangijuman",
    nomiKirill: "Сангижуман",
    aholi: 2045,
    xonadon: 349,
    oila: 570,
    kambagalYanvar: 50,
    kambagalJami: 69,
    davlatTaminotida: 21,
    kambagalOilalar: 35,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 769,
    band: 802,
    ishsiz: 40,
    ayollarDaftari: 21,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 25,
    nomi: "Maydon",
    nomiKirill: "Майдон",
    aholi: 2065,
    xonadon: 351,
    oila: 571,
    kambagalYanvar: 42,
    kambagalJami: 74,
    davlatTaminotida: 40,
    kambagalOilalar: 35,
    kambagallikChegarasida: 4,
    mehnatgaLayoqatli: 777,
    band: 803,
    ishsiz: 53,
    ayollarDaftari: 26,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 26,
    nomi: "Yangi",
    nomiKirill: "Янги",
    aholi: 2867,
    xonadon: 581,
    oila: 687,
    kambagalYanvar: 46,
    kambagalJami: 85,
    davlatTaminotida: 27,
    kambagalOilalar: 41,
    kambagallikChegarasida: 19,
    mehnatgaLayoqatli: 1079,
    band: 999,
    ishsiz: 46,
    ayollarDaftari: 25,
    ijtimoiyReestr: 5,
    migratsiyadanQaytgan: 8,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 27,
    nomi: "Saroy",
    nomiKirill: "Сарой",
    aholi: 2389,
    xonadon: 580,
    oila: 780,
    kambagalYanvar: 51,
    kambagalJami: 77,
    davlatTaminotida: 34,
    kambagalOilalar: 47,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 899,
    band: 750,
    ishsiz: 29,
    ayollarDaftari: 18,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 28,
    nomi: "Madaniyat",
    nomiKirill: "Маданият",
    aholi: 2630,
    xonadon: 507,
    oila: 763,
    kambagalYanvar: 44,
    kambagalJami: 59,
    davlatTaminotida: 16,
    kambagalOilalar: 49,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 990,
    band: 802,
    ishsiz: 43,
    ayollarDaftari: 21,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 29,
    nomi: "Paraxun",
    nomiKirill: "Парахун",
    aholi: 3532,
    xonadon: 615,
    oila: 882,
    kambagalYanvar: 62,
    kambagalJami: 77,
    davlatTaminotida: 30,
    kambagalOilalar: 50,
    kambagallikChegarasida: 7,
    mehnatgaLayoqatli: 1329,
    band: 1303,
    ishsiz: 67,
    ayollarDaftari: 26,
    ijtimoiyReestr: 30,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 30,
    nomi: "Bog'chakalon",
    nomiKirill: "Боғчакалон",
    aholi: 3197,
    xonadon: 625,
    oila: 783,
    kambagalYanvar: 66,
    kambagalJami: 80,
    davlatTaminotida: 24,
    kambagalOilalar: 48,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 1203,
    band: 1127,
    ishsiz: 55,
    ayollarDaftari: 30,
    ijtimoiyReestr: 15,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 31,
    nomi: "Ikrom Karvon",
    nomiKirill: "Икром Карвон",
    aholi: 3023,
    xonadon: 543,
    oila: 733,
    kambagalYanvar: 60,
    kambagalJami: 74,
    davlatTaminotida: 23,
    kambagalOilalar: 40,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1138,
    band: 1061,
    ishsiz: 54,
    ayollarDaftari: 36,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 32,
    nomi: "Jaloyir",
    nomiKirill: "Жалойир",
    aholi: 3152,
    xonadon: 648,
    oila: 870,
    kambagalYanvar: 59,
    kambagalJami: 94,
    davlatTaminotida: 47,
    kambagalOilalar: 49,
    kambagallikChegarasida: 6,
    mehnatgaLayoqatli: 1186,
    band: 1080,
    ishsiz: 43,
    ayollarDaftari: 29,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 33,
    nomi: "Uchqora",
    nomiKirill: "Учқора",
    aholi: 4423,
    xonadon: 770,
    oila: 1078,
    kambagalYanvar: 84,
    kambagalJami: 102,
    davlatTaminotida: 38,
    kambagalOilalar: 62,
    kambagallikChegarasida: 18,
    mehnatgaLayoqatli: 1665,
    band: 1621,
    ishsiz: 61,
    ayollarDaftari: 39,
    ijtimoiyReestr: 12,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 34,
    nomi: "Qo'shchinor",
    nomiKirill: "Қўшчинор",
    aholi: 3201,
    xonadon: 635,
    oila: 794,
    kambagalYanvar: 54,
    kambagalJami: 72,
    davlatTaminotida: 28,
    kambagalOilalar: 45,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1205,
    band: 1119,
    ishsiz: 61,
    ayollarDaftari: 30,
    ijtimoiyReestr: 13,
    migratsiyadanQaytgan: 12,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 35,
    nomi: "Binokor",
    nomiKirill: "Бинокор",
    aholi: 2676,
    xonadon: 524,
    oila: 637,
    kambagalYanvar: 38,
    kambagalJami: 51,
    davlatTaminotida: 8,
    kambagalOilalar: 36,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1007,
    band: 742,
    ishsiz: 54,
    ayollarDaftari: 29,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 36,
    nomi: "Polvonota",
    nomiKirill: "Полвонота",
    aholi: 2374,
    xonadon: 512,
    oila: 710,
    kambagalYanvar: 62,
    kambagalJami: 98,
    davlatTaminotida: 41,
    kambagalOilalar: 37,
    kambagallikChegarasida: 27,
    mehnatgaLayoqatli: 893,
    band: 810,
    ishsiz: 55,
    ayollarDaftari: 37,
    ijtimoiyReestr: 8,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 37,
    nomi: "Miyonqol",
    nomiKirill: "Миёнқол",
    aholi: 2470,
    xonadon: 512,
    oila: 603,
    kambagalYanvar: 48,
    kambagalJami: 65,
    davlatTaminotida: 21,
    kambagalOilalar: 31,
    kambagallikChegarasida: 14,
    mehnatgaLayoqatli: 929,
    band: 861,
    ishsiz: 50,
    ayollarDaftari: 28,
    ijtimoiyReestr: 7,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 38,
    nomi: "Kattasoy",
    nomiKirill: "Каттасой",
    aholi: 2228,
    xonadon: 407,
    oila: 647,
    kambagalYanvar: 70,
    kambagalJami: 76,
    davlatTaminotida: 30,
    kambagalOilalar: 34,
    kambagallikChegarasida: 21,
    mehnatgaLayoqatli: 838,
    band: 838,
    ishsiz: 32,
    ayollarDaftari: 13,
    ijtimoiyReestr: 8,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 39,
    nomi: "Samarqand",
    nomiKirill: "Самарқанд",
    aholi: 2376,
    xonadon: 505,
    oila: 593,
    kambagalYanvar: 48,
    kambagalJami: 57,
    davlatTaminotida: 26,
    kambagalOilalar: 29,
    kambagallikChegarasida: 4,
    mehnatgaLayoqatli: 894,
    band: 819,
    ishsiz: 47,
    ayollarDaftari: 20,
    ijtimoiyReestr: 15,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 40,
    nomi: "Oltinsoy",
    nomiKirill: "Олтинсой",
    aholi: 4300,
    xonadon: 733,
    oila: 1064,
    kambagalYanvar: 111,
    kambagalJami: 111,
    davlatTaminotida: 40,
    kambagalOilalar: 54,
    kambagallikChegarasida: 25,
    mehnatgaLayoqatli: 1618,
    band: 1594,
    ishsiz: 57,
    ayollarDaftari: 42,
    ijtimoiyReestr: 1,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 41,
    nomi: "Qoracha",
    nomiKirill: "Қорача",
    aholi: 3570,
    xonadon: 718,
    oila: 941,
    kambagalYanvar: 50,
    kambagalJami: 95,
    davlatTaminotida: 36,
    kambagalOilalar: 47,
    kambagallikChegarasida: 16,
    mehnatgaLayoqatli: 1344,
    band: 1229,
    ishsiz: 49,
    ayollarDaftari: 25,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 42,
    nomi: "Oqtepa",
    nomiKirill: "Оқтепа",
    aholi: 1817,
    xonadon: 310,
    oila: 468,
    kambagalYanvar: 36,
    kambagalJami: 46,
    davlatTaminotida: 15,
    kambagalOilalar: 23,
    kambagallikChegarasida: 11,
    mehnatgaLayoqatli: 684,
    band: 679,
    ishsiz: 46,
    ayollarDaftari: 24,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 43,
    nomi: "Yangirabod",
    nomiKirill: "Янгирабод",
    aholi: 4033,
    xonadon: 778,
    oila: 1126,
    kambagalYanvar: 65,
    kambagalJami: 110,
    davlatTaminotida: 40,
    kambagalOilalar: 54,
    kambagallikChegarasida: 11,
    mehnatgaLayoqatli: 1518,
    band: 1410,
    ishsiz: 78,
    ayollarDaftari: 35,
    ijtimoiyReestr: 24,
    migratsiyadanQaytgan: 10,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 44,
    nomi: "Qo'rg'oncha",
    nomiKirill: "Қўрғонча",
    aholi: 3194,
    xonadon: 572,
    oila: 768,
    kambagalYanvar: 61,
    kambagalJami: 90,
    davlatTaminotida: 33,
    kambagalOilalar: 41,
    kambagallikChegarasida: 15,
    mehnatgaLayoqatli: 1202,
    band: 1177,
    ishsiz: 48,
    ayollarDaftari: 35,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 45,
    nomi: "Istiqlol",
    nomiKirill: "Истиқлол",
    aholi: 3057,
    xonadon: 661,
    oila: 751,
    kambagalYanvar: 55,
    kambagalJami: 63,
    davlatTaminotida: 15,
    kambagalOilalar: 38,
    kambagallikChegarasida: 16,
    mehnatgaLayoqatli: 1150,
    band: 1018,
    ishsiz: 54,
    ayollarDaftari: 35,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 46,
    nomi: "Tinchlik",
    nomiKirill: "Тинчлик",
    aholi: 2505,
    xonadon: 512,
    oila: 706,
    kambagalYanvar: 47,
    kambagalJami: 59,
    davlatTaminotida: 15,
    kambagalOilalar: 33,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 943,
    band: 878,
    ishsiz: 34,
    ayollarDaftari: 20,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 47,
    nomi: "Bunyodkor",
    nomiKirill: "Бунёдкор",
    aholi: 2198,
    xonadon: 460,
    oila: 621,
    kambagalYanvar: 39,
    kambagalJami: 60,
    davlatTaminotida: 26,
    kambagalOilalar: 29,
    kambagallikChegarasida: 3,
    mehnatgaLayoqatli: 827,
    band: 771,
    ishsiz: 49,
    ayollarDaftari: 23,
    ijtimoiyReestr: 13,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 48,
    nomi: "Baxshijar",
    nomiKirill: "Бахшижар",
    aholi: 2929,
    xonadon: 601,
    oila: 863,
    kambagalYanvar: 77,
    kambagalJami: 88,
    davlatTaminotida: 34,
    kambagalOilalar: 40,
    kambagallikChegarasida: 19,
    mehnatgaLayoqatli: 1102,
    band: 1010,
    ishsiz: 80,
    ayollarDaftari: 33,
    ijtimoiyReestr: 30,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 49,
    nomi: "Xonaqa",
    nomiKirill: "Хонақа",
    aholi: 1712,
    xonadon: 338,
    oila: 555,
    kambagalYanvar: 29,
    kambagalJami: 37,
    davlatTaminotida: 15,
    kambagalOilalar: 24,
    kambagallikChegarasida: 1,
    mehnatgaLayoqatli: 644,
    band: 639,
    ishsiz: 26,
    ayollarDaftari: 16,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 50,
    nomi: "Guliston",
    nomiKirill: "Гулистон",
    aholi: 3468,
    xonadon: 564,
    oila: 812,
    kambagalYanvar: 58,
    kambagalJami: 75,
    davlatTaminotida: 34,
    kambagalOilalar: 38,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1305,
    band: 1329,
    ishsiz: 44,
    ayollarDaftari: 30,
    ijtimoiyReestr: 2,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 51,
    nomi: "Toshquloq",
    nomiKirill: "Тошқулоқ",
    aholi: 2726,
    xonadon: 514,
    oila: 649,
    kambagalYanvar: 44,
    kambagalJami: 47,
    davlatTaminotida: 27,
    kambagalOilalar: 27,
    kambagallikChegarasida: 3,
    mehnatgaLayoqatli: 1026,
    band: 992,
    ishsiz: 33,
    ayollarDaftari: 20,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 52,
    nomi: "Zarafshon",
    nomiKirill: "Зарафшон",
    aholi: 2480,
    xonadon: 507,
    oila: 741,
    kambagalYanvar: 39,
    kambagalJami: 61,
    davlatTaminotida: 29,
    kambagalOilalar: 31,
    kambagallikChegarasida: 4,
    mehnatgaLayoqatli: 933,
    band: 870,
    ishsiz: 44,
    ayollarDaftari: 17,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 53,
    nomi: "Do'stlik",
    nomiKirill: "Дўстлик",
    aholi: 2464,
    xonadon: 671,
    oila: 821,
    kambagalYanvar: 69,
    kambagalJami: 82,
    davlatTaminotida: 38,
    kambagalOilalar: 33,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 927,
    band: 699,
    ishsiz: 49,
    ayollarDaftari: 15,
    ijtimoiyReestr: 25,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 54,
    nomi: "Navbahor",
    nomiKirill: "Навбаҳор",
    aholi: 3392,
    xonadon: 601,
    oila: 684,
    kambagalYanvar: 55,
    kambagalJami: 67,
    davlatTaminotida: 36,
    kambagalOilalar: 27,
    kambagallikChegarasida: 9,
    mehnatgaLayoqatli: 1277,
    band: 1044,
    ishsiz: 46,
    ayollarDaftari: 30,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 55,
    nomi: "Dehqonobod",
    nomiKirill: "Деҳқонобод",
    aholi: 3271,
    xonadon: 565,
    oila: 735,
    kambagalYanvar: 48,
    kambagalJami: 57,
    davlatTaminotida: 24,
    kambagalOilalar: 29,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1231,
    band: 1225,
    ishsiz: 39,
    ayollarDaftari: 20,
    ijtimoiyReestr: 4,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 56,
    nomi: "Novja",
    nomiKirill: "Новжа",
    aholi: 2171,
    xonadon: 411,
    oila: 571,
    kambagalYanvar: 37,
    kambagalJami: 48,
    davlatTaminotida: 26,
    kambagalOilalar: 22,
    kambagallikChegarasida: 6,
    mehnatgaLayoqatli: 817,
    band: 806,
    ishsiz: 38,
    ayollarDaftari: 21,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 57,
    nomi: "Olmazor",
    nomiKirill: "Олмазор",
    aholi: 2120,
    xonadon: 432,
    oila: 646,
    kambagalYanvar: 42,
    kambagalJami: 53,
    davlatTaminotida: 20,
    kambagalOilalar: 27,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 798,
    band: 758,
    ishsiz: 44,
    ayollarDaftari: 26,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 58,
    nomi: "Tasmachi",
    nomiKirill: "Тасмачи",
    aholi: 4631,
    xonadon: 787,
    oila: 1175,
    kambagalYanvar: 65,
    kambagalJami: 79,
    davlatTaminotida: 34,
    kambagalOilalar: 45,
    kambagallikChegarasida: 17,
    mehnatgaLayoqatli: 1743,
    band: 1713,
    ishsiz: 44,
    ayollarDaftari: 30,
    ijtimoiyReestr: 1,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 59,
    nomi: "Bog'ishamol",
    nomiKirill: "Боғишамол",
    aholi: 2280,
    xonadon: 564,
    oila: 738,
    kambagalYanvar: 50,
    kambagalJami: 51,
    davlatTaminotida: 22,
    kambagalOilalar: 27,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 858,
    band: 710,
    ishsiz: 31,
    ayollarDaftari: 17,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 60,
    nomi: "Angidon",
    nomiKirill: "Ангидон",
    aholi: 2267,
    xonadon: 387,
    oila: 544,
    kambagalYanvar: 35,
    kambagalJami: 47,
    davlatTaminotida: 24,
    kambagalOilalar: 21,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 853,
    band: 879,
    ishsiz: 40,
    ayollarDaftari: 20,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 61,
    nomi: "Tamabaxrin",
    nomiKirill: "Тамабахрин",
    aholi: 2513,
    xonadon: 612,
    oila: 725,
    kambagalYanvar: 42,
    kambagalJami: 56,
    davlatTaminotida: 24,
    kambagalOilalar: 22,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 946,
    band: 783,
    ishsiz: 33,
    ayollarDaftari: 20,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 62,
    nomi: "Qo'rg'ontepa",
    nomiKirill: "Қўрғонтепа",
    aholi: 2053,
    xonadon: 391,
    oila: 493,
    kambagalYanvar: 25,
    kambagalJami: 37,
    davlatTaminotida: 21,
    kambagalOilalar: 15,
    kambagallikChegarasida: 3,
    mehnatgaLayoqatli: 772,
    band: 738,
    ishsiz: 40,
    ayollarDaftari: 29,
    ijtimoiyReestr: 2,
    migratsiyadanQaytgan: 1,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 63,
    nomi: "Mirzo Ulug'bek",
    nomiKirill: "Мирзо Улуғбек",
    aholi: 2397,
    xonadon: 506,
    oila: 705,
    kambagalYanvar: 45,
    kambagalJami: 42,
    davlatTaminotida: 20,
    kambagalOilalar: 20,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 902,
    band: 920,
    ishsiz: 33,
    ayollarDaftari: 20,
    ijtimoiyReestr: 2,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 64,
    nomi: "Chinobod",
    nomiKirill: "Чинобод",
    aholi: 2814,
    xonadon: 528,
    oila: 804,
    kambagalYanvar: 49,
    kambagalJami: 53,
    davlatTaminotida: 24,
    kambagalOilalar: 21,
    kambagallikChegarasida: 11,
    mehnatgaLayoqatli: 1059,
    band: 991,
    ishsiz: 47,
    ayollarDaftari: 30,
    ijtimoiyReestr: 1,
    migratsiyadanQaytgan: 8,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 65,
    nomi: "Fidokor",
    nomiKirill: "Фидокор",
    aholi: 2473,
    xonadon: 517,
    oila: 696,
    kambagalYanvar: 28,
    kambagalJami: 53,
    davlatTaminotida: 27,
    kambagalOilalar: 18,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 931,
    band: 857,
    ishsiz: 43,
    ayollarDaftari: 20,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 66,
    nomi: "Mirishkor",
    nomiKirill: "Миришкор",
    aholi: 3120,
    xonadon: 708,
    oila: 837,
    kambagalYanvar: 49,
    kambagalJami: 46,
    davlatTaminotida: 22,
    kambagalOilalar: 20,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 1157,
    band: 1004,
    ishsiz: 29,
    ayollarDaftari: 14,
    ijtimoiyReestr: 1,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 67,
    nomi: "Yangi qurilish",
    nomiKirill: "Янги Қурилиш",
    aholi: 2494,
    xonadon: 512,
    oila: 738,
    kambagalYanvar: 53,
    kambagalJami: 38,
    davlatTaminotida: 18,
    kambagalOilalar: 18,
    kambagallikChegarasida: 7,
    mehnatgaLayoqatli: 938,
    band: 861,
    ishsiz: 41,
    ayollarDaftari: 23,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 8,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 68,
    nomi: "Navro'z",
    nomiKirill: "Наврўз",
    aholi: 3152,
    xonadon: 636,
    oila: 758,
    kambagalYanvar: 32,
    kambagalJami: 49,
    davlatTaminotida: 19,
    kambagalOilalar: 17,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 1186,
    band: 1092,
    ishsiz: 48,
    ayollarDaftari: 29,
    ijtimoiyReestr: 4,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 69,
    nomi: "Chechak ota",
    nomiKirill: "Чечакота",
    aholi: 2703,
    xonadon: 580,
    oila: 853,
    kambagalYanvar: 34,
    kambagalJami: 39,
    davlatTaminotida: 19,
    kambagalOilalar: 19,
    kambagallikChegarasida: 7,
    mehnatgaLayoqatli: 1017,
    band: 913,
    ishsiz: 14,
    ayollarDaftari: 11,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 1,
    oliyBitiruvchi: 1,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 70,
    nomi: "Avoqli",
    nomiKirill: "Авоқли",
    aholi: 3340,
    xonadon: 715,
    oila: 911,
    kambagalYanvar: 66,
    kambagalJami: 48,
    davlatTaminotida: 20,
    kambagalOilalar: 14,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1257,
    band: 1105,
    ishsiz: 52,
    ayollarDaftari: 27,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  }
];

/** Faqat nomlar - qidiruv va ro'yxatlar uchun */
export const MAHALLALAR = MAHALLALAR_BAZASI.map((m) => m.nomi);

/** Tuman bo'yicha jami - hokim panelidagi maxrajlar */
export const TUMAN_JAMI = MAHALLALAR_BAZASI.reduce(
  (jami, m) => ({
    aholi: jami.aholi + m.aholi,
    xonadon: jami.xonadon + m.xonadon,
    oila: jami.oila + m.oila,
    kambagalJami: jami.kambagalJami + m.kambagalJami,
    mehnatgaLayoqatli: jami.mehnatgaLayoqatli + m.mehnatgaLayoqatli,
    band: jami.band + m.band,
    ishsiz: jami.ishsiz + m.ishsiz,
    ayollarDaftari: jami.ayollarDaftari + m.ayollarDaftari,
    ijtimoiyReestr: jami.ijtimoiyReestr + m.ijtimoiyReestr,
    migratsiyadanQaytgan: jami.migratsiyadanQaytgan + m.migratsiyadanQaytgan,
  }),
  {
    aholi: 0, xonadon: 0, oila: 0, kambagalJami: 0, mehnatgaLayoqatli: 0,
    band: 0, ishsiz: 0, ayollarDaftari: 0, ijtimoiyReestr: 0, migratsiyadanQaytgan: 0,
  }
);
