/**
 * ============================================================
 *  XATIRCHI TUMANI - 70 TA MFY, RAISLAR VA BAZA STATISTIKASI
 *
 *  Ikki manba birlashtirilgan:
 *
 *  1. TASDIQLANGAN MAHALLA RAISLARI RO'YXATI - MFY raisining
 *     F.I.SH., telefoni, ma'lumoti va aholi/oila/xonadon soni.
 *     Bu ro'yxat rasmiy tasdiqlangan, shuning uchun aholi
 *     raqamlarida u USTUN turadi.
 *
 *  2. Svod jadvali (31.08.2026) - kambag'allik va ishsizlik
 *     raqamlari. Bular birinchi ro'yxatda yo'q.
 *
 *  Diqqat: ikki manba xonadon sonida farq qiladi (37 ta MFY da,
 *  ba'zilarida 200 dan ortiq). Tasdiqlangan ro'yxat olindi -
 *  chunki qamrov foizining MAXRAJI aynan shu raqam va u rasmiy
 *  hujjatga mos kelishi kerak.
 *
 *  Bu raqamlar QAMROV FOIZINING MAXRAJI. Ularsiz platforma faqat
 *  o'zi yig'ganini sanay oladi; ular bilan esa "51 ta ishsizdan
 *  38 tasi xatlovdan o'tdi = 75%" deb ayta oladi. Aynan shu
 *  ko'rsatkich hokimga qaysi mahalla orqada qolayotganini
 *  ko'rsatadi.
 *
 *  Nomlar ikki alifboda saqlanadi: anketa kirillda to'ldiriladi
 *  (xodim qo'lidagi qog'oz kirill), panel esa lotinda ko'rsatadi.
 * ============================================================
 */

export interface MahallaBazasi {
  /** Svod jadvalidagi tartib raqami */
  tartib: number;
  nomi: string;
  nomiKirill: string;
  /** MFY raisi - tasdiqlangan ro'yxatdan */
  raisFish: string;
  raisTelefon: string;
  raisMalumoti: string;
  aholi: number;
  xonadon: number;
  oila: number;
  /** 01.01.2026 holatiga kambag'al oilalar */
  kambagalYanvar: number;
  /** 01.08.2026 holatiga umumiy kambag'al oilalar */
  kambagalJami: number;
  davlatTaminotida: number;
  kambagalOilalar: number;
  kambagallikChegarasida: number;
  mehnatgaLayoqatli: number;
  band: number;
  /** Ishsizlar soni - platformaning asosiy maxraji */
  ishsiz: number;
  ayollarDaftari: number;
  ijtimoiyReestr: number;
  migratsiyadanQaytgan: number;
  oliyBitiruvchi: number;
  ortaMaxsusBitiruvchi: number;
  maktabBitiruvchi: number;
}

export const MAHALLALAR_BAZASI: MahallaBazasi[] = [
  {
    tartib: 1,
    nomi: "Uyshun",
    nomiKirill: "Уйшун",
    raisFish: "Шоназаров Ахмад Шоназарович",
    raisTelefon: "+998956242022",
    raisMalumoti: "тугалланмаган олий",
    aholi: 2582,
    xonadon: 515,
    oila: 630,
    kambagalYanvar: 59,
    kambagalJami: 128,
    davlatTaminotida: 34,
    kambagalOilalar: 88,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 972,
    band: 925,
    ishsiz: 51,
    ayollarDaftari: 20,
    ijtimoiyReestr: 22,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 2,
    nomi: "Alisher Navoiy",
    nomiKirill: "Алишер Навоий",
    raisFish: "Тўрақулов Умиджон Салохиддинович",
    raisTelefon: "+998880857297",
    raisMalumoti: "олий",
    aholi: 3512,
    xonadon: 845,
    oila: 928,
    kambagalYanvar: 99,
    kambagalJami: 145,
    davlatTaminotida: 49,
    kambagalOilalar: 93,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1322,
    band: 1146,
    ishsiz: 66,
    ayollarDaftari: 35,
    ijtimoiyReestr: 18,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 3,
    nomi: "Xo'jaqulobod",
    nomiKirill: "Хўжақулобод",
    raisFish: "Ботиров Сардор Собир ўғли",
    raisTelefon: "+998930860992",
    raisMalumoti: "тугалланмаган олий",
    aholi: 3489,
    xonadon: 857,
    oila: 905,
    kambagalYanvar: 94,
    kambagalJami: 153,
    davlatTaminotida: 57,
    kambagalOilalar: 88,
    kambagallikChegarasida: 18,
    mehnatgaLayoqatli: 1313,
    band: 1241,
    ishsiz: 64,
    ayollarDaftari: 25,
    ijtimoiyReestr: 27,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 4,
    nomi: "Amir Temur",
    nomiKirill: "Амир Темур",
    raisFish: "Хўжаназаров Абдурасул Махаматович",
    raisTelefon: "+998931561084",
    raisMalumoti: "тугалланмаган олий",
    aholi: 3482,
    xonadon: 626,
    oila: 688,
    kambagalYanvar: 78,
    kambagalJami: 115,
    davlatTaminotida: 25,
    kambagalOilalar: 74,
    kambagallikChegarasida: 17,
    mehnatgaLayoqatli: 1310,
    band: 1272,
    ishsiz: 43,
    ayollarDaftari: 18,
    ijtimoiyReestr: 14,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 5,
    nomi: "Bo'g'irdoq",
    nomiKirill: "Буғирдоқ",
    raisFish: "Худойқулов Азимжон Актамович",
    raisTelefon: "+998919916263",
    raisMalumoti: "олий",
    aholi: 3115,
    xonadon: 649,
    oila: 874,
    kambagalYanvar: 70,
    kambagalJami: 118,
    davlatTaminotida: 25,
    kambagalOilalar: 78,
    kambagallikChegarasida: 18,
    mehnatgaLayoqatli: 1172,
    band: 1060,
    ishsiz: 40,
    ayollarDaftari: 25,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 6,
    nomi: "Oltinobod",
    nomiKirill: "Олтинобод",
    raisFish: "Турсунов Одилжон Сайдиёрович",
    raisTelefon: "+998945307626",
    raisMalumoti: "ўрта махсус",
    aholi: 3210,
    xonadon: 697,
    oila: 913,
    kambagalYanvar: 73,
    kambagalJami: 106,
    davlatTaminotida: 30,
    kambagalOilalar: 77,
    kambagallikChegarasida: 15,
    mehnatgaLayoqatli: 1208,
    band: 1098,
    ishsiz: 41,
    ayollarDaftari: 28,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 7,
    nomi: "Koriz Arab",
    nomiKirill: "Кориз Араб",
    raisFish: "Хушвақов Бахриддин Қувондиқович",
    raisTelefon: "+998939531633",
    raisMalumoti: "тугалланмаган олий",
    aholi: 2820,
    xonadon: 556,
    oila: 612,
    kambagalYanvar: 62,
    kambagalJami: 93,
    davlatTaminotida: 30,
    kambagalOilalar: 59,
    kambagallikChegarasida: 16,
    mehnatgaLayoqatli: 1061,
    band: 1007,
    ishsiz: 44,
    ayollarDaftari: 20,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 8,
    nomi: "Damariq",
    nomiKirill: "Дамариқ",
    raisFish: "Мусаев Холбой Дўсбоевич",
    raisTelefon: "+998906193589",
    raisMalumoti: "олий",
    aholi: 3072,
    xonadon: 567,
    oila: 601,
    kambagalYanvar: 84,
    kambagalJami: 112,
    davlatTaminotida: 49,
    kambagalOilalar: 55,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1156,
    band: 1086,
    ishsiz: 62,
    ayollarDaftari: 30,
    ijtimoiyReestr: 21,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 9,
    nomi: "Quchchi",
    nomiKirill: "Қуччи",
    raisFish: "Нуриддинов Дилшод Қодирович",
    raisTelefon: "+998993760711",
    raisMalumoti: "олий",
    aholi: 2080,
    xonadon: 447,
    oila: 597,
    kambagalYanvar: 61,
    kambagalJami: 87,
    davlatTaminotida: 28,
    kambagalOilalar: 52,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 783,
    band: 731,
    ishsiz: 44,
    ayollarDaftari: 27,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 1,
    oliyBitiruvchi: 2,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 10,
    nomi: "Mustaqillik",
    nomiKirill: "Мустақиллик",
    raisFish: "Ортиқов Салохиддин Махаматович",
    raisTelefon: "+998948648788",
    raisMalumoti: "тугалланмаган олий",
    aholi: 4503,
    xonadon: 748,
    oila: 891,
    kambagalYanvar: 77,
    kambagalJami: 97,
    davlatTaminotida: 29,
    kambagalOilalar: 76,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 1695,
    band: 1645,
    ishsiz: 62,
    ayollarDaftari: 15,
    ijtimoiyReestr: 36,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 11,
    nomi: "Galabek",
    nomiKirill: "Галабек",
    raisFish: "Пардаев Равшанжон Юлдошевич",
    raisTelefon: "+998882287452",
    raisMalumoti: "тугалланмаган олий",
    aholi: 3428,
    xonadon: 562,
    oila: 803,
    kambagalYanvar: 61,
    kambagalJami: 98,
    davlatTaminotida: 29,
    kambagalOilalar: 64,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1290,
    band: 1310,
    ishsiz: 87,
    ayollarDaftari: 36,
    ijtimoiyReestr: 33,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 9,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 12,
    nomi: "Chag'atoy",
    nomiKirill: "Чағатой",
    raisFish: "Толлиев Бахтиёр Худоярович",
    raisTelefon: "+998501007218",
    raisMalumoti: "тугалланмаган олий",
    aholi: 3112,
    xonadon: 546,
    oila: 896,
    kambagalYanvar: 51,
    kambagalJami: 95,
    davlatTaminotida: 30,
    kambagalOilalar: 59,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1171,
    band: 1011,
    ishsiz: 54,
    ayollarDaftari: 25,
    ijtimoiyReestr: 19,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 13,
    nomi: "Xo'jaqo'rg'on",
    nomiKirill: "Хўжақўрғон",
    raisFish: "Ражабов Шахбоз Ғуломжон ўғли",
    raisTelefon: "+998880861244",
    raisMalumoti: "олий",
    aholi: 2522,
    xonadon: 578,
    oila: 791,
    kambagalYanvar: 44,
    kambagalJami: 93,
    davlatTaminotida: 24,
    kambagalOilalar: 59,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 949,
    band: 822,
    ishsiz: 57,
    ayollarDaftari: 33,
    ijtimoiyReestr: 12,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 14,
    nomi: "Nayman",
    nomiKirill: "Найман",
    raisFish: "Эргашев Ҳамдам Рустамович",
    raisTelefon: "+998934634502",
    raisMalumoti: "ўрта махсус",
    aholi: 3080,
    xonadon: 564,
    oila: 765,
    kambagalYanvar: 53,
    kambagalJami: 89,
    davlatTaminotida: 30,
    kambagalOilalar: 50,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 1159,
    band: 1150,
    ishsiz: 49,
    ayollarDaftari: 22,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 8,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 15,
    nomi: "Mirdosh",
    nomiKirill: "Мирдош",
    raisFish: "Суяров Баҳодир Аннақулович",
    raisTelefon: "+998933193275",
    raisMalumoti: "олий",
    aholi: 2397,
    xonadon: 507,
    oila: 655,
    kambagalYanvar: 65,
    kambagalJami: 87,
    davlatTaminotida: 28,
    kambagalOilalar: 46,
    kambagallikChegarasida: 18,
    mehnatgaLayoqatli: 1174,
    band: 921,
    ishsiz: 43,
    ayollarDaftari: 20,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 16,
    nomi: "Paxtakor",
    nomiKirill: "Пахтакор",
    raisFish: "Ҳамраев Комилжон Бахриддинович",
    raisTelefon: "+998943791213",
    raisMalumoti: "олий",
    aholi: 2533,
    xonadon: 518,
    oila: 627,
    kambagalYanvar: 44,
    kambagalJami: 67,
    davlatTaminotida: 22,
    kambagalOilalar: 46,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 953,
    band: 883,
    ishsiz: 39,
    ayollarDaftari: 28,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 17,
    nomi: "Changir",
    nomiKirill: "Чангир",
    raisFish: "Мардонов Шохрух Баҳодир  ўғли",
    raisTelefon: "+998933164000",
    raisMalumoti: "олий",
    aholi: 2781,
    xonadon: 540,
    oila: 679,
    kambagalYanvar: 67,
    kambagalJami: 95,
    davlatTaminotida: 34,
    kambagalOilalar: 54,
    kambagallikChegarasida: 15,
    mehnatgaLayoqatli: 1047,
    band: 789,
    ishsiz: 47,
    ayollarDaftari: 22,
    ijtimoiyReestr: 14,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 18,
    nomi: "Langar",
    nomiKirill: "Лангар",
    raisFish: "Мадатова Онара Джўрақуловна",
    raisTelefon: "+998939514052",
    raisMalumoti: "тугалланмаган олий",
    aholi: 2808,
    xonadon: 614,
    oila: 644,
    kambagalYanvar: 75,
    kambagalJami: 90,
    davlatTaminotida: 33,
    kambagalOilalar: 43,
    kambagallikChegarasida: 23,
    mehnatgaLayoqatli: 1057,
    band: 934,
    ishsiz: 44,
    ayollarDaftari: 13,
    ijtimoiyReestr: 18,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 19,
    nomi: "Ko'ksaroy",
    nomiKirill: "Кўксарой",
    raisFish: "Мирзаев Илҳом Суюндикович",
    raisTelefon: "+998997777972",
    raisMalumoti: "тугалланмаган олий",
    aholi: 3179,
    xonadon: 609,
    oila: 823,
    kambagalYanvar: 70,
    kambagalJami: 105,
    davlatTaminotida: 40,
    kambagalOilalar: 56,
    kambagallikChegarasida: 14,
    mehnatgaLayoqatli: 1196,
    band: 1082,
    ishsiz: 68,
    ayollarDaftari: 33,
    ijtimoiyReestr: 22,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 20,
    nomi: "Farovon",
    nomiKirill: "Фаровон",
    raisFish: "Тангатаров Музроф Шодиевич",
    raisTelefon: "+998913315503",
    raisMalumoti: "олий",
    aholi: 1764,
    xonadon: 595,
    oila: 673,
    kambagalYanvar: 59,
    kambagalJami: 86,
    davlatTaminotida: 34,
    kambagalOilalar: 48,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 664,
    band: 431,
    ishsiz: 34,
    ayollarDaftari: 10,
    ijtimoiyReestr: 14,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 21,
    nomi: "Zarbdor",
    nomiKirill: "Зарбдор",
    raisFish: "Шамсиев Зариф Зокирович",
    raisTelefon: "+998934330463",
    raisMalumoti: "олий",
    aholi: 2351,
    xonadon: 520,
    oila: 669,
    kambagalYanvar: 38,
    kambagalJami: 72,
    davlatTaminotida: 28,
    kambagalOilalar: 49,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 885,
    band: 745,
    ishsiz: 43,
    ayollarDaftari: 21,
    ijtimoiyReestr: 8,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 22,
    nomi: "Uchtepa",
    nomiKirill: "Учтепа",
    raisFish: "Турсунов Илёс Маҳмадолиевич",
    raisTelefon: "+998880562288",
    raisMalumoti: "олий",
    aholi: 3147,
    xonadon: 526,
    oila: 792,
    kambagalYanvar: 62,
    kambagalJami: 81,
    davlatTaminotida: 19,
    kambagalOilalar: 47,
    kambagallikChegarasida: 16,
    mehnatgaLayoqatli: 1184,
    band: 1200,
    ishsiz: 64,
    ayollarDaftari: 30,
    ijtimoiyReestr: 22,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 23,
    nomi: "Oq-oltin",
    nomiKirill: "Оқ Олтин",
    raisFish: "Тошпўлатов Рустам Жўрақулович",
    raisTelefon: "+998944832894",
    raisMalumoti: "олий",
    aholi: 3630,
    xonadon: 544,
    oila: 677,
    kambagalYanvar: 52,
    kambagalJami: 80,
    davlatTaminotida: 27,
    kambagalOilalar: 47,
    kambagallikChegarasida: 11,
    mehnatgaLayoqatli: 1366,
    band: 1036,
    ishsiz: 56,
    ayollarDaftari: 30,
    ijtimoiyReestr: 8,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 24,
    nomi: "Sangijuman",
    nomiKirill: "Сангижуман",
    raisFish: "Қорақулов Алишер Мамаражабович",
    raisTelefon: "+998993803183",
    raisMalumoti: "ўрта махсус",
    aholi: 2045,
    xonadon: 349,
    oila: 522,
    kambagalYanvar: 50,
    kambagalJami: 69,
    davlatTaminotida: 21,
    kambagalOilalar: 35,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 769,
    band: 802,
    ishsiz: 40,
    ayollarDaftari: 21,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 25,
    nomi: "Maydon",
    nomiKirill: "Майдон",
    raisFish: "Суяров Шавкат Сайфиддинович",
    raisTelefon: "+998996507386",
    raisMalumoti: "олий",
    aholi: 2470,
    xonadon: 512,
    oila: 586,
    kambagalYanvar: 42,
    kambagalJami: 74,
    davlatTaminotida: 40,
    kambagalOilalar: 35,
    kambagallikChegarasida: 4,
    mehnatgaLayoqatli: 777,
    band: 803,
    ishsiz: 53,
    ayollarDaftari: 26,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 26,
    nomi: "Yangi",
    nomiKirill: "Янги",
    raisFish: "Сафаров Олимжон Рахматуллаевич",
    raisTelefon: "+998949710471",
    raisMalumoti: "олий",
    aholi: 2867,
    xonadon: 584,
    oila: 671,
    kambagalYanvar: 46,
    kambagalJami: 85,
    davlatTaminotida: 27,
    kambagalOilalar: 41,
    kambagallikChegarasida: 19,
    mehnatgaLayoqatli: 1079,
    band: 999,
    ishsiz: 46,
    ayollarDaftari: 25,
    ijtimoiyReestr: 5,
    migratsiyadanQaytgan: 8,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 27,
    nomi: "Saroy",
    nomiKirill: "Сарой",
    raisFish: "Бобоқулов Бунёд Тўрақулович",
    raisTelefon: "+998939521535",
    raisMalumoti: "олий",
    aholi: 2389,
    xonadon: 581,
    oila: 802,
    kambagalYanvar: 51,
    kambagalJami: 77,
    davlatTaminotida: 34,
    kambagalOilalar: 47,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 899,
    band: 750,
    ishsiz: 29,
    ayollarDaftari: 18,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 28,
    nomi: "Madaniyat",
    nomiKirill: "Маданият",
    raisFish: "Эшназаров Бекзод Эркинович",
    raisTelefon: "+998993843774",
    raisMalumoti: "олий",
    aholi: 2065,
    xonadon: 359,
    oila: 585,
    kambagalYanvar: 44,
    kambagalJami: 59,
    davlatTaminotida: 16,
    kambagalOilalar: 49,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 990,
    band: 802,
    ishsiz: 43,
    ayollarDaftari: 21,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 29,
    nomi: "Paraxun",
    nomiKirill: "Парахун",
    raisFish: "Солиева Мархабо Рахматовна",
    raisTelefon: "+998943742262",
    raisMalumoti: "олий",
    aholi: 3532,
    xonadon: 620,
    oila: 842,
    kambagalYanvar: 62,
    kambagalJami: 77,
    davlatTaminotida: 30,
    kambagalOilalar: 50,
    kambagallikChegarasida: 7,
    mehnatgaLayoqatli: 1329,
    band: 1303,
    ishsiz: 67,
    ayollarDaftari: 26,
    ijtimoiyReestr: 30,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 30,
    nomi: "Bog'chakalon",
    nomiKirill: "Боғчакалон",
    raisFish: "Хошимов Нодирбек Мамаражабович",
    raisTelefon: "+998873580087",
    raisMalumoti: "олий",
    aholi: 3197,
    xonadon: 678,
    oila: 829,
    kambagalYanvar: 66,
    kambagalJami: 80,
    davlatTaminotida: 24,
    kambagalOilalar: 48,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 1203,
    band: 1127,
    ishsiz: 55,
    ayollarDaftari: 30,
    ijtimoiyReestr: 15,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 31,
    nomi: "Ikrom Karvon",
    nomiKirill: "Икром Карвон",
    raisFish: "Аслонов Хуршид Ўктамқулович",
    raisTelefon: "+998943788737",
    raisMalumoti: "тугалланмаган олий",
    aholi: 3023,
    xonadon: 721,
    oila: 803,
    kambagalYanvar: 60,
    kambagalJami: 74,
    davlatTaminotida: 23,
    kambagalOilalar: 40,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1138,
    band: 1061,
    ishsiz: 54,
    ayollarDaftari: 36,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 32,
    nomi: "Jaloyir",
    nomiKirill: "Жалойир",
    raisFish: "Эргашев Фарход Эшназарович",
    raisTelefon: "+998942521742",
    raisMalumoti: "олий",
    aholi: 3152,
    xonadon: 648,
    oila: 820,
    kambagalYanvar: 59,
    kambagalJami: 94,
    davlatTaminotida: 47,
    kambagalOilalar: 49,
    kambagallikChegarasida: 6,
    mehnatgaLayoqatli: 1186,
    band: 1080,
    ishsiz: 43,
    ayollarDaftari: 29,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 33,
    nomi: "Uchqora",
    nomiKirill: "Учқора",
    raisFish: "Ғаниев Бектош Сағдуллаевич",
    raisTelefon: "+998771307410",
    raisMalumoti: "тугалланмаган олий",
    aholi: 4423,
    xonadon: 770,
    oila: 1102,
    kambagalYanvar: 84,
    kambagalJami: 102,
    davlatTaminotida: 38,
    kambagalOilalar: 62,
    kambagallikChegarasida: 18,
    mehnatgaLayoqatli: 1665,
    band: 1621,
    ishsiz: 61,
    ayollarDaftari: 39,
    ijtimoiyReestr: 12,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 34,
    nomi: "Qo'shchinor",
    nomiKirill: "Қўшчинор",
    raisFish: "Мухторов Салохиддин Жалолович",
    raisTelefon: "+998933161563",
    raisMalumoti: "олий",
    aholi: 3201,
    xonadon: 635,
    oila: 775,
    kambagalYanvar: 54,
    kambagalJami: 72,
    davlatTaminotida: 28,
    kambagalOilalar: 45,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1205,
    band: 1119,
    ishsiz: 61,
    ayollarDaftari: 30,
    ijtimoiyReestr: 13,
    migratsiyadanQaytgan: 12,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 35,
    nomi: "Binokor",
    nomiKirill: "Бинокор",
    raisFish: "Урунова Гуландом Рахмоновна",
    raisTelefon: "+998910870709",
    raisMalumoti: "ўрта махсус",
    aholi: 2676,
    xonadon: 521,
    oila: 674,
    kambagalYanvar: 38,
    kambagalJami: 51,
    davlatTaminotida: 8,
    kambagalOilalar: 36,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1007,
    band: 742,
    ishsiz: 54,
    ayollarDaftari: 29,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 36,
    nomi: "Polvonota",
    nomiKirill: "Полвонота",
    raisFish: "Ибрагимов Зарифжон Умрзоқович",
    raisTelefon: "+998943773326",
    raisMalumoti: "олий",
    aholi: 2374,
    xonadon: 512,
    oila: 715,
    kambagalYanvar: 62,
    kambagalJami: 98,
    davlatTaminotida: 41,
    kambagalOilalar: 37,
    kambagallikChegarasida: 27,
    mehnatgaLayoqatli: 893,
    band: 810,
    ishsiz: 55,
    ayollarDaftari: 37,
    ijtimoiyReestr: 8,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 5,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 37,
    nomi: "Miyonqol",
    nomiKirill: "Миёнқол",
    raisFish: "Ахматов Обид Ҳамидович",
    raisTelefon: "+998997580886",
    raisMalumoti: "ўрта махсус",
    aholi: 2344,
    xonadon: 470,
    oila: 612,
    kambagalYanvar: 48,
    kambagalJami: 65,
    davlatTaminotida: 21,
    kambagalOilalar: 31,
    kambagallikChegarasida: 14,
    mehnatgaLayoqatli: 929,
    band: 861,
    ishsiz: 50,
    ayollarDaftari: 28,
    ijtimoiyReestr: 7,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 38,
    nomi: "Kattasoy",
    nomiKirill: "Каттасой",
    raisFish: "Эсанов Рахимжон Эргашевич",
    raisTelefon: "+998993361283",
    raisMalumoti: "олий",
    aholi: 2228,
    xonadon: 483,
    oila: 600,
    kambagalYanvar: 70,
    kambagalJami: 76,
    davlatTaminotida: 30,
    kambagalOilalar: 34,
    kambagallikChegarasida: 21,
    mehnatgaLayoqatli: 838,
    band: 838,
    ishsiz: 32,
    ayollarDaftari: 13,
    ijtimoiyReestr: 8,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 39,
    nomi: "Samarqand",
    nomiKirill: "Самарқанд",
    raisFish: "Содиқов Қутлуғжон Маҳмудович",
    raisTelefon: "+998933103773",
    raisMalumoti: "олий",
    aholi: 2376,
    xonadon: 505,
    oila: 542,
    kambagalYanvar: 48,
    kambagalJami: 57,
    davlatTaminotida: 26,
    kambagalOilalar: 29,
    kambagallikChegarasida: 4,
    mehnatgaLayoqatli: 894,
    band: 819,
    ishsiz: 47,
    ayollarDaftari: 20,
    ijtimoiyReestr: 15,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 40,
    nomi: "Oltinsoy",
    nomiKirill: "Олтинсой",
    raisFish: "Ҳакимов Суннатилла Ёқубович",
    raisTelefon: "+998991146185",
    raisMalumoti: "тугалланмаган олий",
    aholi: 4300,
    xonadon: 733,
    oila: 1021,
    kambagalYanvar: 111,
    kambagalJami: 111,
    davlatTaminotida: 40,
    kambagalOilalar: 54,
    kambagallikChegarasida: 25,
    mehnatgaLayoqatli: 1618,
    band: 1594,
    ishsiz: 57,
    ayollarDaftari: 42,
    ijtimoiyReestr: 1,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 41,
    nomi: "Qoracha",
    nomiKirill: "Қорача",
    raisFish: "Розиқов Жамшид Абдикомилович",
    raisTelefon: "+998994626137",
    raisMalumoti: "олий",
    aholi: 3570,
    xonadon: 718,
    oila: 890,
    kambagalYanvar: 50,
    kambagalJami: 95,
    davlatTaminotida: 36,
    kambagalOilalar: 47,
    kambagallikChegarasida: 16,
    mehnatgaLayoqatli: 1344,
    band: 1229,
    ishsiz: 49,
    ayollarDaftari: 25,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 42,
    nomi: "Oqtepa",
    nomiKirill: "Оқтепа",
    raisFish: "Қаноатов Баҳодир Абдуахатович",
    raisTelefon: "+998996606851",
    raisMalumoti: "олий",
    aholi: 1817,
    xonadon: 320,
    oila: 506,
    kambagalYanvar: 36,
    kambagalJami: 46,
    davlatTaminotida: 15,
    kambagalOilalar: 23,
    kambagallikChegarasida: 11,
    mehnatgaLayoqatli: 684,
    band: 679,
    ishsiz: 46,
    ayollarDaftari: 24,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 43,
    nomi: "Yangirabod",
    nomiKirill: "Янгирабод",
    raisFish: "Зиётов Зиёдулла Содиқович",
    raisTelefon: "+998906207848",
    raisMalumoti: "ўрта махсус",
    aholi: 4033,
    xonadon: 778,
    oila: 1058,
    kambagalYanvar: 65,
    kambagalJami: 110,
    davlatTaminotida: 40,
    kambagalOilalar: 54,
    kambagallikChegarasida: 11,
    mehnatgaLayoqatli: 1518,
    band: 1410,
    ishsiz: 78,
    ayollarDaftari: 35,
    ijtimoiyReestr: 24,
    migratsiyadanQaytgan: 10,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 44,
    nomi: "Qo'rg'oncha",
    nomiKirill: "Қўрғонча",
    raisFish: "Жўраев Абдурашит Шомуродович",
    raisTelefon: "+998973206061",
    raisMalumoti: "олий",
    aholi: 3194,
    xonadon: 572,
    oila: 689,
    kambagalYanvar: 61,
    kambagalJami: 90,
    davlatTaminotida: 33,
    kambagalOilalar: 41,
    kambagallikChegarasida: 15,
    mehnatgaLayoqatli: 1202,
    band: 1177,
    ishsiz: 48,
    ayollarDaftari: 35,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 45,
    nomi: "Istiqlol",
    nomiKirill: "Истиқлол",
    raisFish: "Шерназаров Баҳодир Умарович",
    raisTelefon: "+998944874310",
    raisMalumoti: "олий",
    aholi: 3057,
    xonadon: 663,
    oila: 705,
    kambagalYanvar: 55,
    kambagalJami: 63,
    davlatTaminotida: 15,
    kambagalOilalar: 38,
    kambagallikChegarasida: 16,
    mehnatgaLayoqatli: 1150,
    band: 1018,
    ishsiz: 54,
    ayollarDaftari: 35,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 46,
    nomi: "Tinchlik",
    nomiKirill: "Тинчлик",
    raisFish: "Эшниёзова Шафоат Эркиновна",
    raisTelefon: "+998939522734",
    raisMalumoti: "олий",
    aholi: 2505,
    xonadon: 516,
    oila: 655,
    kambagalYanvar: 47,
    kambagalJami: 59,
    davlatTaminotida: 15,
    kambagalOilalar: 33,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 943,
    band: 878,
    ishsiz: 34,
    ayollarDaftari: 20,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 2,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 47,
    nomi: "Bunyodkor",
    nomiKirill: "Бунёдкор",
    raisFish: "Тўхтамуродов Акмал Бобонорович",
    raisTelefon: "+998944847599",
    raisMalumoti: "олий",
    aholi: 2198,
    xonadon: 510,
    oila: 650,
    kambagalYanvar: 39,
    kambagalJami: 60,
    davlatTaminotida: 26,
    kambagalOilalar: 29,
    kambagallikChegarasida: 3,
    mehnatgaLayoqatli: 827,
    band: 771,
    ishsiz: 49,
    ayollarDaftari: 23,
    ijtimoiyReestr: 13,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 48,
    nomi: "Baxshijar",
    nomiKirill: "Бахшижар",
    raisFish: "Рахмонбердиев Азизбек Зарифович",
    raisTelefon: "+998991515085",
    raisMalumoti: "ўрта махсус",
    aholi: 2929,
    xonadon: 602,
    oila: 820,
    kambagalYanvar: 77,
    kambagalJami: 88,
    davlatTaminotida: 34,
    kambagalOilalar: 40,
    kambagallikChegarasida: 19,
    mehnatgaLayoqatli: 1102,
    band: 1010,
    ishsiz: 80,
    ayollarDaftari: 33,
    ijtimoiyReestr: 30,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 49,
    nomi: "Xonaqa",
    nomiKirill: "Хонақа",
    raisFish: "Холмуродов Камолиддин Исмоилович",
    raisTelefon: "+998907323444",
    raisMalumoti: "олий",
    aholi: 1712,
    xonadon: 338,
    oila: 505,
    kambagalYanvar: 29,
    kambagalJami: 37,
    davlatTaminotida: 15,
    kambagalOilalar: 24,
    kambagallikChegarasida: 1,
    mehnatgaLayoqatli: 644,
    band: 639,
    ishsiz: 26,
    ayollarDaftari: 16,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 50,
    nomi: "Guliston",
    nomiKirill: "Гулистон",
    raisFish: "Тешаева Мархабо Номозовна",
    raisTelefon: "+998936218179",
    raisMalumoti: "олий",
    aholi: 3468,
    xonadon: 564,
    oila: 769,
    kambagalYanvar: 58,
    kambagalJami: 75,
    davlatTaminotida: 34,
    kambagalOilalar: 38,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 1305,
    band: 1329,
    ishsiz: 44,
    ayollarDaftari: 30,
    ijtimoiyReestr: 2,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 51,
    nomi: "Toshquloq",
    nomiKirill: "Тошқулоқ",
    raisFish: "Қаршиев Фарход Холиқул ўғли",
    raisTelefon: "+998945472818",
    raisMalumoti: "олий",
    aholi: 2726,
    xonadon: 514,
    oila: 606,
    kambagalYanvar: 44,
    kambagalJami: 47,
    davlatTaminotida: 27,
    kambagalOilalar: 27,
    kambagallikChegarasida: 3,
    mehnatgaLayoqatli: 1026,
    band: 992,
    ishsiz: 33,
    ayollarDaftari: 20,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 52,
    nomi: "Zarafshon",
    nomiKirill: "Зарафшон",
    raisFish: "Эшмуродов Бектош Бахриддинович",
    raisTelefon: "+998934312720",
    raisMalumoti: "олий",
    aholi: 2480,
    xonadon: 616,
    oila: 795,
    kambagalYanvar: 39,
    kambagalJami: 61,
    davlatTaminotida: 29,
    kambagalOilalar: 31,
    kambagallikChegarasida: 4,
    mehnatgaLayoqatli: 933,
    band: 870,
    ishsiz: 44,
    ayollarDaftari: 17,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 53,
    nomi: "Do'stlik",
    nomiKirill: "Дўстлик",
    raisFish: "Сафаров Одилжон Отақулович",
    raisTelefon: "+998934308084",
    raisMalumoti: "олий",
    aholi: 2464,
    xonadon: 671,
    oila: 770,
    kambagalYanvar: 69,
    kambagalJami: 82,
    davlatTaminotida: 38,
    kambagalOilalar: 33,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 927,
    band: 699,
    ishsiz: 49,
    ayollarDaftari: 15,
    ijtimoiyReestr: 25,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 4,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 54,
    nomi: "Navbahor",
    nomiKirill: "Навбаҳор",
    raisFish: "Абдуаҳадов Абдусамад Абдуаҳадович",
    raisTelefon: "+998991021466",
    raisMalumoti: "тугалланмаган олий",
    aholi: 3392,
    xonadon: 630,
    oila: 782,
    kambagalYanvar: 55,
    kambagalJami: 67,
    davlatTaminotida: 36,
    kambagalOilalar: 27,
    kambagallikChegarasida: 9,
    mehnatgaLayoqatli: 1277,
    band: 1044,
    ishsiz: 46,
    ayollarDaftari: 30,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 55,
    nomi: "Dehqonobod",
    nomiKirill: "Деҳқонобод",
    raisFish: "Нуритдинов Сирожиддин Умарович",
    raisTelefon: "+998942220155",
    raisMalumoti: "тугалланмаган олий",
    aholi: 3271,
    xonadon: 565,
    oila: 690,
    kambagalYanvar: 48,
    kambagalJami: 57,
    davlatTaminotida: 24,
    kambagalOilalar: 29,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1231,
    band: 1225,
    ishsiz: 39,
    ayollarDaftari: 20,
    ijtimoiyReestr: 4,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 56,
    nomi: "Novja",
    nomiKirill: "Новжа",
    raisFish: "Жонизоқов Равшанжон Олимжонович",
    raisTelefon: "+998933190037",
    raisMalumoti: "олий",
    aholi: 2171,
    xonadon: 412,
    oila: 520,
    kambagalYanvar: 37,
    kambagalJami: 48,
    davlatTaminotida: 26,
    kambagalOilalar: 22,
    kambagallikChegarasida: 6,
    mehnatgaLayoqatli: 817,
    band: 806,
    ishsiz: 38,
    ayollarDaftari: 21,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 57,
    nomi: "Olmazor",
    nomiKirill: "Олмазор",
    raisFish: "Мавлонов Садирдин Очилович",
    raisTelefon: "+998939552623",
    raisMalumoti: "олий",
    aholi: 2120,
    xonadon: 432,
    oila: 631,
    kambagalYanvar: 42,
    kambagalJami: 53,
    davlatTaminotida: 20,
    kambagalOilalar: 27,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 798,
    band: 758,
    ishsiz: 44,
    ayollarDaftari: 26,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 58,
    nomi: "Tasmachi",
    nomiKirill: "Тасмачи",
    raisFish: "Пармонов Комилжон Примқулович",
    raisTelefon: "+998946664401",
    raisMalumoti: "олий",
    aholi: 4631,
    xonadon: 787,
    oila: 1125,
    kambagalYanvar: 65,
    kambagalJami: 79,
    davlatTaminotida: 34,
    kambagalOilalar: 45,
    kambagallikChegarasida: 17,
    mehnatgaLayoqatli: 1743,
    band: 1713,
    ishsiz: 44,
    ayollarDaftari: 30,
    ijtimoiyReestr: 1,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 59,
    nomi: "Bog'ishamol",
    nomiKirill: "Боғишамол",
    raisFish: "Тўраев Шуҳрат Ғайбуллаевич",
    raisTelefon: "+998943156202",
    raisMalumoti: "ўрта махсус",
    aholi: 2280,
    xonadon: 564,
    oila: 687,
    kambagalYanvar: 50,
    kambagalJami: 51,
    davlatTaminotida: 22,
    kambagalOilalar: 27,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 858,
    band: 710,
    ishsiz: 31,
    ayollarDaftari: 17,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 4,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 60,
    nomi: "Angidon",
    nomiKirill: "Ангидон",
    raisFish: "Рўзиев Ҳайитмурод Бахронович",
    raisTelefon: "+998934626371",
    raisMalumoti: "тугалланмаган олий",
    aholi: 2267,
    xonadon: 420,
    oila: 524,
    kambagalYanvar: 35,
    kambagalJami: 47,
    davlatTaminotida: 24,
    kambagalOilalar: 21,
    kambagallikChegarasida: 10,
    mehnatgaLayoqatli: 853,
    band: 879,
    ishsiz: 40,
    ayollarDaftari: 20,
    ijtimoiyReestr: 9,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 61,
    nomi: "Tamabaxrin",
    nomiKirill: "Тамабахрин",
    raisFish: "Маматов Анвар Исомиддинович",
    raisTelefon: "+998942530020",
    raisMalumoti: "олий",
    aholi: 2513,
    xonadon: 613,
    oila: 683,
    kambagalYanvar: 42,
    kambagalJami: 56,
    davlatTaminotida: 24,
    kambagalOilalar: 22,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 946,
    band: 783,
    ishsiz: 33,
    ayollarDaftari: 20,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 6,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 62,
    nomi: "Qo'rg'ontepa",
    nomiKirill: "Қўрғонтепа",
    raisFish: "Шайматов Ибройим Тўхташевич",
    raisTelefon: "+998991837281",
    raisMalumoti: "олий",
    aholi: 2053,
    xonadon: 393,
    oila: 486,
    kambagalYanvar: 25,
    kambagalJami: 37,
    davlatTaminotida: 21,
    kambagalOilalar: 15,
    kambagallikChegarasida: 3,
    mehnatgaLayoqatli: 772,
    band: 738,
    ishsiz: 40,
    ayollarDaftari: 29,
    ijtimoiyReestr: 2,
    migratsiyadanQaytgan: 1,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 63,
    nomi: "Mirzo Ulug'bek",
    nomiKirill: "Мирзо Улуғбек",
    raisFish: "Абдурайимов Насирдин Нематиллаевич",
    raisTelefon: "+998957217507",
    raisMalumoti: "олий",
    aholi: 2630,
    xonadon: 520,
    oila: 740,
    kambagalYanvar: 45,
    kambagalJami: 42,
    davlatTaminotida: 20,
    kambagalOilalar: 20,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 902,
    band: 920,
    ishsiz: 33,
    ayollarDaftari: 20,
    ijtimoiyReestr: 2,
    migratsiyadanQaytgan: 3,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 2,
    maktabBitiruvchi: 0
  },
  {
    tartib: 64,
    nomi: "Chinobod",
    nomiKirill: "Чинобод",
    raisFish: "Ниёзов Нуриддин Очилович",
    raisTelefon: "+998944800676",
    raisMalumoti: "олий",
    aholi: 2814,
    xonadon: 545,
    oila: 772,
    kambagalYanvar: 49,
    kambagalJami: 53,
    davlatTaminotida: 24,
    kambagalOilalar: 21,
    kambagallikChegarasida: 11,
    mehnatgaLayoqatli: 1059,
    band: 991,
    ishsiz: 47,
    ayollarDaftari: 30,
    ijtimoiyReestr: 1,
    migratsiyadanQaytgan: 8,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 65,
    nomi: "Fidokor",
    nomiKirill: "Фидокор",
    raisFish: "Мажидов Юнус Нормаматович",
    raisTelefon: "+998951312100",
    raisMalumoti: "олий",
    aholi: 2473,
    xonadon: 524,
    oila: 648,
    kambagalYanvar: 28,
    kambagalJami: 53,
    davlatTaminotida: 27,
    kambagalOilalar: 18,
    kambagallikChegarasida: 8,
    mehnatgaLayoqatli: 931,
    band: 857,
    ishsiz: 43,
    ayollarDaftari: 20,
    ijtimoiyReestr: 10,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 66,
    nomi: "Mirishkor",
    nomiKirill: "Миришкор",
    raisFish: "Ғайбуллаев Зохид Муҳаммадиевич",
    raisTelefon: "+998933500086",
    raisMalumoti: "олий",
    aholi: 3120,
    xonadon: 708,
    oila: 787,
    kambagalYanvar: 49,
    kambagalJami: 46,
    davlatTaminotida: 22,
    kambagalOilalar: 20,
    kambagallikChegarasida: 5,
    mehnatgaLayoqatli: 1157,
    band: 1004,
    ishsiz: 29,
    ayollarDaftari: 14,
    ijtimoiyReestr: 1,
    migratsiyadanQaytgan: 7,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 67,
    nomi: "Yangi qurilish",
    nomiKirill: "Янги Қурилиш",
    raisFish: "Жумаев Маъруф Рахимович",
    raisTelefon: "+998943776066",
    raisMalumoti: "олий",
    aholi: 2494,
    xonadon: 512,
    oila: 791,
    kambagalYanvar: 53,
    kambagalJami: 38,
    davlatTaminotida: 18,
    kambagalOilalar: 18,
    kambagallikChegarasida: 7,
    mehnatgaLayoqatli: 938,
    band: 861,
    ishsiz: 41,
    ayollarDaftari: 23,
    ijtimoiyReestr: 3,
    migratsiyadanQaytgan: 8,
    oliyBitiruvchi: 6,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 68,
    nomi: "Navro'z",
    nomiKirill: "Наврўз",
    raisFish: "Абжалилов Мансур Ҳусанович",
    raisTelefon: "+998880800950",
    raisMalumoti: "олий",
    aholi: 3152,
    xonadon: 636,
    oila: 712,
    kambagalYanvar: 32,
    kambagalJami: 49,
    davlatTaminotida: 19,
    kambagalOilalar: 17,
    kambagallikChegarasida: 12,
    mehnatgaLayoqatli: 1186,
    band: 1092,
    ishsiz: 48,
    ayollarDaftari: 29,
    ijtimoiyReestr: 4,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 7,
    ortaMaxsusBitiruvchi: 3,
    maktabBitiruvchi: 0
  },
  {
    tartib: 69,
    nomi: "Chechak ota",
    nomiKirill: "Чечакота",
    raisFish: "Тошева Муқаддас Исроиловна",
    raisTelefon: "+998933148006",
    raisMalumoti: "олий",
    aholi: 2703,
    xonadon: 580,
    oila: 803,
    kambagalYanvar: 34,
    kambagalJami: 39,
    davlatTaminotida: 19,
    kambagalOilalar: 19,
    kambagallikChegarasida: 7,
    mehnatgaLayoqatli: 1017,
    band: 913,
    ishsiz: 14,
    ayollarDaftari: 11,
    ijtimoiyReestr: 0,
    migratsiyadanQaytgan: 1,
    oliyBitiruvchi: 1,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  },
  {
    tartib: 70,
    nomi: "Avoqli",
    nomiKirill: "Авоқли",
    raisFish: "Абдуғаниев Жаҳонгир Абдуғаниевич",
    raisTelefon: "+998942224878",
    raisMalumoti: "олий",
    aholi: 3340,
    xonadon: 743,
    oila: 950,
    kambagalYanvar: 66,
    kambagalJami: 48,
    davlatTaminotida: 20,
    kambagalOilalar: 14,
    kambagallikChegarasida: 13,
    mehnatgaLayoqatli: 1257,
    band: 1105,
    ishsiz: 52,
    ayollarDaftari: 27,
    ijtimoiyReestr: 11,
    migratsiyadanQaytgan: 5,
    oliyBitiruvchi: 8,
    ortaMaxsusBitiruvchi: 1,
    maktabBitiruvchi: 0
  }
];

/** Faqat nomlar - qidiruv va ro'yxatlar uchun */
export const MAHALLALAR = MAHALLALAR_BAZASI.map((m) => m.nomi);

/** Tuman bo'yicha jami - hokim panelidagi maxrajlar */
export const TUMAN_JAMI = MAHALLALAR_BAZASI.reduce(
  (jami, m) => ({
    aholi: jami.aholi + m.aholi,
    xonadon: jami.xonadon + m.xonadon,
    oila: jami.oila + m.oila,
    kambagalJami: jami.kambagalJami + m.kambagalJami,
    mehnatgaLayoqatli: jami.mehnatgaLayoqatli + m.mehnatgaLayoqatli,
    band: jami.band + m.band,
    ishsiz: jami.ishsiz + m.ishsiz,
    ayollarDaftari: jami.ayollarDaftari + m.ayollarDaftari,
    ijtimoiyReestr: jami.ijtimoiyReestr + m.ijtimoiyReestr,
    migratsiyadanQaytgan: jami.migratsiyadanQaytgan + m.migratsiyadanQaytgan,
  }),
  {
    aholi: 0, xonadon: 0, oila: 0, kambagalJami: 0, mehnatgaLayoqatli: 0,
    band: 0, ishsiz: 0, ayollarDaftari: 0, ijtimoiyReestr: 0, migratsiyadanQaytgan: 0,
  }
);
